{
 "title": "worldPing Endpoint: |--- DNS",
 "tags": [
  "worldPing",
  "Endpoints"
 ],
 "time": { "from": "now-3h", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "endpoint", "label": "Endpoint", "query": "worldping.*" },
   { "name": "probe", "label": "Probe(s)", "query": "worldping.$endpoint.*" },
   { "name": "outliers", "label": "Outliers", "query": "100,99.9,99.5,99,95,50" }
  ]
 },
 "panels": [
  { "title": "nav", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "worldping-endpoint-nav", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "ping status for $endpoint (all selected Probes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "DNS HEALTH (LAST)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(health.$endpoint.dns.ok_state)"
    }
   ]
  },
  {
   "title": "DNS UPTIME",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(averageSeries(worldping.$endpoint.$probe.dns.ok_state), 100)"
    }
   ]
  },
  {
   "title": "DNS ANSWERS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(worldping.$endpoint.$probe.dns.answers)"
    }
   ]
  },
  {
   "title": "DNS LATENCY",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(worldping.$endpoint.$probe.dns.time)"
    }
   ]
  },
  { "title": "Events  (ALL SELECTED PROBES)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "DNS PERFORMANCE (EACH INDIVIDUAL PROBE)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms", "label": "latency" }
   ],
   "targets": [
    {
     "target": "aliasByNode(removeAbovePercentile(worldping.$endpoint.$probe.dns.time, $outliers), 2)"
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 10 },
   "valueName": "total",
   "targets": [
    {
     "target": "aliasByNode(removeBelowValue(consolidateBy(worldping.$endpoint.$probe.dns.error_state, 'sum'), 1), 2)"
    }
   ]
  },
  {
   "title": "DNS ERRORS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 21 },
   "targets": [
    {
     "target": "aliasByNode(removeBelowValue(consolidateBy(worldping.$endpoint.$probe.dns.error_state, 'sum'), 1), 2)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "DNS EVENTS",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "raw_document"
      }
     ],
     "query": "tags.endpoint:$endpoint AND tags.collector:$probe AND tags.monitor_type:dns",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}