{
 "title": "worldPing Endpoint: Summary",
 "tags": [
  "worldPing",
  "Endpoints"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "endpoint", "label": "Endpoint", "query": "worldping.*" },
   { "name": "probe", "label": "Probe(s)", "query": "worldping.$endpoint.*" }
  ]
 },
 "panels": [
  { "title": "nav", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "worldping-endpoint-nav", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 } },
  { "title": "Uptime:", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "DNS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(averageSeries(worldping.$endpoint.$probe.dns.ok_state), 100)"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(averageSeries(worldping.$endpoint.$probe.ping.ok_state), 100)"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(averageSeries(worldping.$endpoint.$probe.http.ok_state), 100)"
    }
   ]
  },
  {
   "title": "HTTPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(averageSeries(worldping.$endpoint.$probe.https.ok_state), 100)"
    }
   ]
  },
  { "title": "Status:", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "DNS",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "alias(consolidateBy(sumSeries(worldping.$endpoint.$probe.dns.error_state), 'sum'), 'error')"
    },
    {
     "target": "alias(consolidateBy(sumSeries(worldping.$endpoint.$probe.dns.ok_state), 'sum'), 'ok')"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "target": "alias(consolidateBy(sumSeries(worldping.$endpoint.$probe.ping.error_state), 'sum'), 'error')"
    },
    {
     "target": "alias(consolidateBy(sumSeries(worldping.$endpoint.$probe.ping.ok_state), 'sum'), 'ok')"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "alias(consolidateBy(sumSeries(worldping.$endpoint.$probe.http.error_state), 'sum'), 'error')"
    },
    {
     "target": "alias(consolidateBy(sumSeries(worldping.$endpoint.$probe.http.ok_state), 'sum'), 'ok')"
    }
   ]
  },
  {
   "title": "HTTPS",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "target": "alias(consolidateBy(sumSeries(worldping.$endpoint.$probe.https.error_state), 'sum'), 'error')"
    },
    {
     "target": "alias(consolidateBy(sumSeries(worldping.$endpoint.$probe.https.ok_state), 'sum'), 'ok')"
    }
   ]
  },
  { "title": "Performance:", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "DNS response by Probe",
   "type": "graph",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByName(worldping.$endpoint.$probe.dns.time), 2)"
    }
   ]
  },
  {
   "title": "Ping response by Probe",
   "type": "graph",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByName(worldping.$endpoint.$probe.ping.mean), 2)"
    }
   ]
  },
  {
   "title": "HTTP response by Probe",
   "type": "graph",
   "gridPos": { "h": 15, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByName(worldping.$endpoint.$probe.http.total), 2)"
    }
   ]
  },
  {
   "title": "HTTPS response by Probe",
   "type": "graph",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByName(worldping.$endpoint.$probe.https.total), 2)"
    }
   ]
  }
 ]
}