{
 "title": "worldPing Endpoint: |--- Ping",
 "tags": [
  "worldPing",
  "Endpoints"
 ],
 "time": { "from": "now-3h", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "endpoint", "label": "Endpoint", "query": "worldping.*" },
   { "name": "probe", "label": "Probe(s)", "query": "worldping.$endpoint.*" },
   { "name": "outliers", "label": "Outliers", "query": "100,99.9,99.5,99,95,50" }
  ]
 },
 "panels": [
  { "type": "worldping-endpoint-nav", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PING HEALTH (LAST)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(health.$endpoint.ping.ok_state)"
    }
   ]
  },
  {
   "title": "PING UPTIME",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(averageSeries(worldping.$endpoint.$probe.ping.ok_state), 100)"
    }
   ]
  },
  {
   "title": "PING PACKET LOSS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(worldping.$endpoint.$probe.ping.loss)"
    }
   ]
  },
  {
   "title": "PING LATENCY",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(worldping.$endpoint.$probe.ping.mean)"
    }
   ]
  },
  {
   "title": "PING PERFORMANCE RANGE AND LOSS (AVERAGE ALL SELECTED PROBES)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms", "label": "latency" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(averageSeries(worldping.$endpoint.$probe.ping.loss), 1), 'loss %')"
    },
    {
     "target": "alias(averageSeries(worldping.$endpoint.$probe.ping.mean), 'average')"
    },
    {
     "target": "alias(consolidateBy(minSeries(worldping.$endpoint.$probe.ping.min), 'min'), 'minimum')"
    },
    {
     "target": "alias(removeAbovePercentile(consolidateBy(maxSeries(worldping.$endpoint.$probe.ping.max), 'max'), $outliers), 'maximum')"
    }
   ]
  },
  {
   "title": "PING PERFORMANCE (EACH INDIVIDUAL PROBE)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms", "label": "latency" }
   ],
   "targets": [
    {
     "target": "aliasByNode(removeAbovePercentile(worldping.$endpoint.$probe.ping.mean, $outliers), 2)"
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "valueName": "total",
   "targets": [
    {
     "target": "aliasByNode(removeBelowValue(consolidateBy(worldping.$endpoint.$probe.ping.error_state, 'sum'), 1), 2)"
    }
   ]
  },
  {
   "title": "PING ERRORS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 25 },
   "targets": [
    {
     "target": "aliasByNode(removeBelowValue(consolidateBy(worldping.$endpoint.$probe.ping.error_state, 'sum'), 1), 2)"
    }
   ]
  },
  {
   "title": "PING EVENTS",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "raw_document"
      }
     ],
     "query": "tags.endpoint:$endpoint AND tags.collector:$probe AND tags.monitor_type:ping",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}