{
 "title": "worldPing Endpoint: |--- Web",
 "tags": [
  "worldPing",
  "Endpoints"
 ],
 "time": { "from": "now-3h", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "endpoint", "label": "Endpoint", "query": "worldping.*" },
   { "name": "probe", "label": "Probe(s)", "query": "worldping.$endpoint.*" },
   { "name": "protocol", "label": "Protocol", "query": "http,https" },
   { "name": "outliers", "label": "Outliers", "query": "100,99.9,99.5,99,95,50" }
  ]
 },
 "panels": [
  { "type": "worldping-endpoint-nav", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WEB HEALTH (LAST)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(health.$endpoint.$protocol.ok_state)"
    }
   ]
  },
  {
   "title": "WEB UPTIME",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(averageSeries(worldping.$endpoint.$probe.$protocol.ok_state), 100)"
    }
   ]
  },
  {
   "title": "WEB RESPONSE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(worldping.$endpoint.$probe.$protocol.total)"
    }
   ]
  },
  {
   "title": "WEB THROUGHPUT",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "target": "averageSeries(worldping.$endpoint.$probe.$protocol.throughput)"
    }
   ]
  },
  {
   "title": "WEB RESPONSE (ALL SELECTED PROBES)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(worldping.$endpoint.$probe.$protocol.dns), 'dns')"
    },
    {
     "target": "alias(averageSeries(worldping.$endpoint.$probe.$protocol.connect), 'connect')"
    },
    {
     "target": "alias(averageSeries(worldping.$endpoint.$probe.$protocol.send), 'send')"
    },
    {
     "target": "alias(averageSeries(worldping.$endpoint.$probe.$protocol.wait), 'wait')"
    },
    {
     "target": "alias(averageSeries(worldping.$endpoint.$probe.$protocol.recv), 'recv')"
    }
   ]
  },
  {
   "title": "WEB THROUGHPUT (ALL SELECTED PROBES)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(worldping.$endpoint.$probe.$protocol.throughput), 'throughput')"
    },
    {
     "target": "alias(averageSeries(worldping.$endpoint.$probe.$protocol.dataLength), 'content size')"
    }
   ]
  },
  {
   "title": "WEB PERFORMANCE",
   "type": "graph",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms", "label": "latency" }
   ],
   "targets": [
    {
     "target": "aliasByNode(removeAbovePercentile(worldping.$endpoint.$probe.$protocol.total, $outliers), 2)"
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "valueName": "total",
   "targets": [
    {
     "target": "aliasByNode(removeBelowValue(consolidateBy(worldping.$endpoint.$probe.$protocol.error_state, 'sum'), 1), 2)"
    }
   ]
  },
  {
   "title": "WEB ERRORS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 25 },
   "targets": [
    {
     "target": "aliasByNode(removeBelowValue(consolidateBy(worldping.$endpoint.$probe.$protocol.error_state, 'sum'), 1), 2)"
    }
   ]
  },
  {
   "title": "WEB EVENTS",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "raw_document"
      }
     ],
     "query": "tags.endpoint:$endpoint AND tags.collector:$probe AND tags.monitor_type:$protocol",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}